const mongoose = require("mongoose");

const laptopSchema = mongoose.Schema(
  {
    productName: String,
    brandName: String,
    category: String,
    productImage: [String],
    key_features: String, 
    description: String,
    processor_brand: String, 
    processor_model: String, 
    processor_frequency: String, 
    processor_core: Number, 
    processor_thread: Number, 
    cpu_cache: String, 
    chipset: String, 
    chipset_model: String, 
    display: String, 
    display_type: String, 
    display_resolution: String, 
    touch_screen: String, 
    refresh_rate: String, 
    display_features: String, 
    ram: Number, 
    ram_type: String, 
    bus_speed: Number, 
    total_ram_slot: Number,
    max_ram_capacity: Number, 
    storage_type: String, 
    storage_capacity: String, 
    extra_m2_slot: String, 
    storage_upgrade: String, 
    graphics_model: String, 
    graphics_memory: Number, 
    graphics_type: String, 
    keyboard_type: String, 
    touchPad: String, 
    webcam: String, 
    speaker: String, 
    microphone: String, 
    audio_features: String, 
    optical_drive: String, 
    card_reader: String, 
    hdmi_port: String, 
    usb_port: String, 
    usb_type_c: String, 
    microphone_port: String, 
    lan: String, 
    wifi: String, 
    bluetooth: String, 
    fingerPrint: String, 
    camera_privacy_shutter: String, 
    security_chip: String, 
    operating_system: String, 
    battery_capacity: String, 
    adapter_type: String, 
    dimensions: String, 
    weight: String, 
    body_material: String, 
    warranty: String, 
    price: Number,
    sellingPrice: Number,
  },
  {
    timestamps: true,
  }
);

const laptopModel = mongoose.model("laptop", laptopSchema);

module.exports = laptopModel;