const productCategory = [
    // {id: 1, label: 'Airpodes', value: 'airpode'}, 
    // {id: 2, label: 'Camera', value: 'camera'}, 
    // {id: 3, label: 'Earphones', value: 'earphone'}, 
    // {id: 4, label: 'Mobiles', value: 'mobile'}, 
    // {id: 5, label: 'Mouse', value: 'mouse'}, 
    // {id: 6, label: 'Printers', value: 'printer'}, 
    // {id: 7, label: 'Processor', value: 'processor'}, 
    // {id: 8, label: 'Refrigerator', value: 'refrigerator'}, 
    // {id: 9, label: 'Speakers', value: 'speaker'}, 
    // {id: 10, label: 'Televisions', value: 'television'}, 
    // {id: 11, label: 'Trimmers', value: 'trimmer'}, 
    // {id: 12, label: 'Watches', value: 'watche'}, 

    {id: 1, label: 'Desktop', value: 'airpode'},
    {id: 2, label: 'Laptop', value: 'laptop'},
    {id: 3, label: 'Compoenent', value: 'component'},
    {id: 4, label: 'Monitor', value: 'monitor'},
    {id: 5, label: 'UPS', value: 'ups'},
    {id: 6, label: 'Phone', value: 'mobile'}, 
    {id: 7, label: 'Tablet', value: 'tablet'}, 
    {id: 8, label: 'Office equipment', value: 'officeEquipment'}, 
    {id: 9, label: 'Camera', value: 'camera'}, 
    {id: 10, label: 'Security', value: 'security'}, 
    {id: 11, label: 'Networking', value: 'networking'}, 
    {id: 12, label: 'Software', value: 'software'}, 
    {id: 13, label: 'Server & Storage', value: 'serverAndStorage'}, 
    {id: 14, label: 'Accessories', value: 'accessories'}, 
    {id: 15, label: 'Gadget', value: 'gadget'}, 
    {id: 16, label: 'Gaming', value: 'Gaming'}, 
    {id: 17, label: 'TV', value: 'television'}, 
    {id: 18, label: 'Appliance', value: 'appliance'}, 

]

export default productCategory;